Project/Areas/Admin/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Project.Areas.Admin.Models;
using Project.Models;
using Project.Utilities;

namespace Project.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/[controller]")]
    public class MenuController : Controller
    {
        private readonly DataContext _dataContext;
        public MenuController(DataContext dataContext)
        {
            _dataContext = dataContext;
        }
        public IActionResult Index()
        {
            if (Functions.IsLogined())
                return NotFound();
            if (!Functions.IsLogin())
                return RedirectToAction("Index", "Login");
            var query = _dataContext.Menus.OrderBy(m => m.MenuID).ToList();
            return View(query);
        }
        [HttpGet]
        [Route("Delete/{id:int}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var m = await _dataContext.Menus.FindAsync(id);
            if (m == null)
            {
                return NotFound();

            }
            return View(m);
        }
        [HttpPost]
        [Route("Delete/{id:int}")]
        public IActionResult Delete(int id)
        {
            var delMenu = _dataContext.Menus.Find(id);
            if (delMenu == null)
            {
                return
                    NotFound();
            }
            _dataContext.Menus.Remove(delMenu);
            _dataContext.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        [Route("Create")]
        public IActionResult Create()
        {
            var query = (from i in _dataContext.Menus
                         select new SelectListItem()
                         {
                             Text = i.MenuName,
                             Value = i.MenuID.ToString(),
                         }).ToList();
            query.Insert(0, new SelectListItem()
            {
                Text = "---Select---",
                Value = "0"
            });
            ViewBag.query = query;
            return View();
        }
        [HttpPost]
        [Route("Create")]
        public async Task<IActionResult> Create(Menu mn)
        {
            if (ModelState.IsValid)
            {
                await _dataContext.Menus.AddAsync(mn);
                await _dataContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(mn);
        }
        [HttpGet]
        [Route("Edit/{id:int}")]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
                return NotFound();
            var sm = _dataContext.Menus.Find(id);
            if (sm == null)
                return NotFound();
            var query = (from i in _dataContext.Menus
                         select new SelectListItem()
                         {
                             Text = i.MenuName,
                             Value = i.MenuID.ToString(),
                         }).ToList();
            query.Insert(0, new SelectListItem()
            {
                Text = "---Select---",
                Value = "0"
            });
            ViewBag.query = query;
            return View(sm);
        }
        [HttpPost]
        [Route("Edit/{id:int}")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Menu mn)
        {
            if (ModelState.IsValid)
            {
                _dataContext.Menus.Update(mn);
                _dataContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mn);
        }
    }
}

Project/Areas/Admin/Controllers/TipController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Project.Models;
using Project.Utilities;

namespace Project.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/[controller]")]
    public class TipController :Controller
    {
        private readonly DataContext _dataContext;
        public TipController(DataContext dataContext)
        {
            _dataContext = dataContext;
        }
        public IActionResult Index()
        {
            if (Functions.IsLogined())
                return NotFound();
            if (!Functions.IsLogin())
                return RedirectToAction("Index", "Login");
            var query = _dataContext.TravelTipss.OrderBy(m => m.TipID).ToList();
            return View(query);
        }
        [HttpGet]
        [Route("Delete/{id:int}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var m = await _dataContext.TravelTipss.FindAsync(id);
            if (m == null)
            {
                return NotFound();

            }
            return View(m);
        }
        [HttpPost]
        [Route("Delete/{id:int}")]
        [ValidateAntiForgeryToken]

        public IActionResult Delete(int id)
        {
            var delTip = _dataContext.TravelTipss.Find(id);
            if (delTip == null)
            {
                return
                    NotFound();
            }
            _dataContext.TravelTipss.Remove(delTip);
            _dataContext.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        [Route("Create")]
        public IActionResult Create()
        {
            var query = (from i in _dataContext.TravelTipss
                         select new SelectListItem()
                         {
                             Text = i.TipTitle,
                             Value = i.TipID.ToString(),
                         }).ToList();
            query.Insert(0, new SelectListItem()
            {
                Text = "---Select---",
                Value = string.Empty
            });
            ViewBag.query = query;
            return View();
        }
        [HttpPost]
        [Route("Create")]
        public async Task<IActionResult> Create(TravelTip tl)
        {
            if (ModelState.IsValid)
            {
                await _dataContext.TravelTipss.AddAsync(tl);
                await _dataContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(tl);
        }
        [HttpGet]
        [Route("Edit/{id:int}")]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
                return NotFound();
            var sm = _dataContext.TravelTipss.Find(id);
            if (sm == null)
                return NotFound();            
            return View(sm);
        }
        [HttpPost]
        [Route("Edit/{id:int}")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(TravelTip tt)
        {
            if (ModelState.IsValid)
            {
                _dataContext.TravelTipss.Update(tt);
                 _dataContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tt);
        }
        [HttpGet]
        [Route("CreatePost")]
        public IActionResult CreatePost()
        {
            var query = (from i in _dataContext.TravelTipss
                         select new SelectListItem()
                         {
                             Text = i.TipTitle,
                             Value = i.TipID.ToString(),
                         }).ToList();
            query.Insert(0, new SelectListItem()
            {
                Text = "---Select---",
                Value = "0"
            });
            ViewBag.query = query;
            return View();
        }
        [HttpPost]
        [Route("CreatePost")]
        public async Task<IActionResult> CreatePost(TravelTip tp)
        {
            if (ModelState.IsValid)
            {
                await _dataContext.TravelTipss.AddAsync(tp);
                await _dataContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(tp);
        }
    }
}

Project/Areas/Admin/Views/Tip/Create.cshtml
@model Project.Models.TravelTip
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class=" main">
    <div class="pagetitle">
        <h2>Thêm nội dung "TravelTips"</h2>
    </div>
    <div class="container shadow p-5">
        <div class="row pb-2">
            <h2>Thêm mới</h2>
        </div>
        <form asp-action="Create" asp-controller="Tip" asp-area="Admin" method="post">
            <div asp-validation-summary="All"></div>
            @Html.AntiForgeryToken()
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="TipTitle">TipTitle</label>
                    <input type="text" class="form-control mb-3" asp-for="TipTitle" placeholder="Insert Tip Title">
                    <span asp-validation-for="TipTitle" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-row">                   
                <div class="form-group col-md-6">
                    <lable asp-for="TipContent">TipContent</lable>
                    @*<input type="text" class="form-control mb-3" asp-for="TipContent" placeholder="Insert TipContent">*@
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="5" asp-for="TipContent" placeholder="Insert TipContent"></textarea>
                    <span asp-validation-for="TipContent" class="alert-danger"></span>
                </div>               
                <div class="form-group mt-5 mb-5">
                    <lable>
                        @Html.CheckBox("IsActive", false)
                        Show
                    </lable>
                </div>
            </div>
            <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i>Save</button>
            <a asp-controller="Tip" asp-action="Index" class=" btn btn-lg btn-warning p-2">Back</a>
        </form>
    </div>
</main>

Project/Areas/Admin/Views/Tip/CreatePost.cshtml
@model Project.Models.TravelTip
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class=" main">
    <div class="pagetitle">
        <h2>Thêm bài viết</h2>
    </div>
    <div class="container shadow p-5">
        <div class="row pb-2">
            <h2>Thêm mới bài viết</h2>
        </div>
        <form asp-action="CreatePost" asp-controller="TravelTip" asp-area="Admin" method="post">
            <div asp-validation-summary="All"></div>
            @Html.AntiForgeryToken()
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="TipTitle">TipTitle</label>
                    <input type="text" class="form-control mb-3" asp-for="TipTitle" placeholder="Insert TipTitle">
                    <span asp-validation-for="TipTitle" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-group col-md-6">
                <lable asp-for="TipContent">tipContent</lable>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="5" asp-for="TipContent" placeholder="Insert TipContent"></textarea>
                <span asp-validation-for="TipContent" class="alert-danger"></span>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <lable asp-for="Levels">Levels</lable>
                    <select asp-for="Levels" class="form-select" id="Levels">
                        <option value="1">0</option>
                        <option value="2">1</option>
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <div class="alert-danger" asp-validation-summary="ModelOnly"></div>
                    <label asp-for="ParentID">ParentID </label>
                    <select asp-for="ParentID" class="form-control"
                            asp-items="@(new SelectList(ViewBag.query,"Value","Text"))">
                    </select>
                </div>
               
                <div class="form-group col-md-6">
                    <lable asp-for="PostOrder">PostOrder</lable>
                    <input type="text" class="form-control mb-3" asp-for="PostOrder" placeholder="Insert PostOrder">
                    <span asp-validation-for="PostOrder" class="alert-danger"></span>
                </div>
                <div class="form-group col-md-12">
                    <lable class="control-lable">Images</lable>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <button class="btn btn-success" type="button" onclick="openDialog()">Choose Image</button>
                        </div>
                        <input type="text" class="form-control" asp-for="Timg" id="file_input" aria-describedby="button-addon2" />
                    </div>
                </div>
                <div class="form-group mt-5 mb-5">
                    <lable>
                        @Html.CheckBox("IsActive", false)
                        Show
                    </lable>
                </div>
            </div>
            <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i>Save</button>
            <a asp-controller="Menu" asp-action="Index" class=" btn btn-lg btn-warning p-2">Back</a>
        </form>
    </div>
</main>
@{
    var summernote = new Project.Areas.Admin.Models.SummerNote("#file_input");
    <partial name="_SummerNote" model="summernote"></partial>
}

Project/Areas/Admin/Views/Tip/Delete.cshtml
@using Project.Models
@model Project.Models.TravelTip
@{
    var tip = Model;
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class="main">
    <div class="pagetitle">
        <h2>Xác nhận xóa?</h2>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <lable asp-for="@tip.TipID">TipID</lable>
            <input value="@tip.TipID" type="text" class=" form-control mb-3" asp-for="TipID" disabled>

        </div>
        <div class="form-group col-md-6">
            <lable asp-for="TipTitle">Tiptitle</lable>
            <input value="@tip.TipTitle" type="text" class=" form-control mb-3" asp-for="TipTitle" disabled>

        </div>
    </div>
    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="TipID" />
        <a class="btn btn-lg btn-warning p-2 mr-5"
           href="javascrip:history.back()">
            <i class="bi bi-arrow-left-circle"></i> Quay lại
        </a>
        <button type="submit" class="btn btn-lg btn-danger p-2">
            <i class="bi bi-trash-fill"></i> Xóa
        </button>
    </form>
</main>

Project/Areas/Admin/Views/Tip/Edit.cshtml
@model Project.Models.TravelTip
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class=" main">
    <div class="pagetitle">
        <h2>Edit TravelTips</h2>
    </div>
    <div class="container shadow p-5">
        <div class="row pb-2">
            <h2>Sửa</h2>
        </div>
        <form asp-action="Edit" method="post" >
            @Html.AntiForgeryToken()
            <div class="form-row">
                <input type="Text" class="form-control mb-3" asp-for="TipID" type="hidden">
                <div class="form-group col-md-6">
                    <label asp-for="TipTitle">TipTitle</label>
                    <input type="text" class="form-control mb-3" asp-for="TipTitle" placeholder="Insert Tip Title">
                    <span asp-validation-for="TipTitle" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-row">      
                <div class="form-group col-md-6">
                    <lable asp-for="TipContent">TipContent</lable>                    
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="5" asp-for="TipContent" placeholder="Insert TipContent"></textarea>
                    <span asp-validation-for="TipContent" class="alert-danger"></span>
                </div>
                <div class="form-group mt-5 mb-5">
                    <lable>
                        @Html.CheckBox("IsActive", Model.IsActive)
                        Show
                    </lable>
                </div>
            </div>
            <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i>Save</button>
            <a asp-controller="Tip" asp-action="Index" class=" btn btn-lg btn-warning p-2">Back</a>
        </form>
    </div>
</main>

Project/Areas/Admin/Views/Tip/Index.cshtml
@using Project.Models
@model IList<TravelTip>
<main id="main" class="main">
    <div class="pagetitle">
        <h2>Travel Tips</h2>
    </div>
   
    <div class="container">
        <div class="d-flex">
            <p class="m-3">
                <a type="button" class="btn btn-success" href="/Admin/Tip/Create">
                    <i class="bi bi-file-earmark-text me-1"></i> Thêm
                </a>
            </p>
            <p class="m-3">
                <a type="button" class="btn btn-success" href="/Admin/Tip/CreatePost">
                    <i class="bi bi-file-earmark-text me-1"></i> Thêm bài viết
                </a>
            </p>
        </div>
    </div>
    <section class="section dashboard">
        <div class="row">

            <!-- Left side columns -->
            <div class="row">
                <!-- Recent Sales -->
                <div class="col-12">
                    <div class="card recent-sales overflow-auto">
                        <div class="card-body mt-4">
                            <table class="table table-borderless datatable">
                                <thead>
                                    <tr>
                                        <th class="col-1 text-center">#</th>
                                        <th class="col-3 text-center">Tiêu đề</th>                                       
                                        <th class="col-2 text-center">Hiện/Ẩn</th>
                                        <th class="col-2 text-center">Chức năng</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <th class="text-center" scope="row">@item.TipID</th>
                                            <td class="text-center">
                                                <a href="#" class="text-primary text-center">@item.TipTitle</a>
                                            </td>
                                            <td class="text-center">@item.IsActive</td>
                                            <td class="text-center">
                                                <a href="/Admin/Tip/Edit/@item.TipID" class="btn btn-primary btn-sm"
                                                   title="Sửa nội dung">
                                                    <i class=" bi bi-pencil"></i>
                                                </a>
                                                <a href="/Admin/Tip/Delete/@item.TipID" class="btn btn-danger btn-sm"
                                                   title="Xóa">
                                                    <i class="bi bi-trash"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    }


                                </tbody>
                            </table>

                        </div>

                    </div>
                </div><!-- End Recent Sales -->
            </div>
        </div>
    </section>
</main>